apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "validator.fullname" . }}
  labels:
  {{- include "validator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
  {{- include "validator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
    {{- include "validator.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: wallet-password
          secret:
            secretName: {{ include "validator.fullname" . }}
      initContainers:
        - name: amazon/aws-cli
          command:
            - "sh"
            - "-c"
            - "yum install -y tar"
            - "&& mkdir {{ .Values.wallet.walletDirectory }}"
            - "&& aws s3 cp {{ .Values.wallet.awsS3Init.walletPath }} {{ .Values.wallet.walletDirectory }}"
            - "&& tar -xvzpf {{ .Values.wallet.walletDirectory }}/*"
            - "&& rm {{ .Values.wallet.walletDirectory }}/*.tar.gz"
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          args:
            - "--beacon-rpc-provider={{ .Values.deployment.beaconNode }}:4000"
            - "--wallet-dir={{ .Values.wallet.walletDirectory }}"
            - "--wallet-password-file={{ .Values.wallet.walletPasswordFilePath }}"
            - "--graffiti={{ .Values.graffiti }}"
            - "--monitoring-host=0.0.0.0"
            - "--monitoring-port={{ .Values.ports.metrics }}"

          volumeMounts:
            - name: wallet-password
              mountPath: {{ .Values.wallet.walletPasswordFilePath }}
              subPath: {{ .Values.wallet.walletSecretSubPath}}
          livenessProbe:
            httpGet:
              path: {{ .Values.deployment.healthEndpoint }}
              port: {{ .Values.ports.metrics }}
          readinessProbe:
            httpGet:
              path: {{ .Values.deployment.healthEndpoint }}
              port: {{ .Values.ports.metrics }}
