nameOverride: ""
fullnameOverride: ""

beaconNode:
  isTestNet: true
  web3HttpProvider: "https://goerli.prylabs.net"
  p2pHostDns: ""
  deployment:
    replicaCount: 1
    podSecurityContext:
      runAsUser: 101
      runAsGroup: 101
      fsGroup: 101
    image:
      repository: "gcr.io/prysmaticlabs/prysm/beacon-chain"
      pullPolicy: Always
      tag: "stable"
    nodeConfigDir: "/config"
    nodeConfigName: "beacon.yaml"
    dataDir: "/data"

stats:
  deployment:
    replicaCount: 1
    image:
      repository: "alethio/eth2stats-client"
      pullPolicy: Always
      tag: "latest"
    eth2StatsAddr: "grpc.medalla.eth2stats.io:443"
    eth2StatsTLS: "true"
    name: "stats-node"
    beaconType: "prysm"
    nodeName: "withte.eth"
    dataPath: "/data"
  persistentVolume:
    size: 5Gi

ports:
  p2pTcp: 13000
  p2pUdp: 12000
  grpc: 4000
  metrics: 8080

storage:
  useStorage: false
  className: microk8s-hostpath

service:
  useTcp: false
  useUdp: false
  type: ClusterIP

