apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "monitoring.fullname" . }}-grafana
  labels: {{- include "monitoring.grafanaLabels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: {{ .Values.grafana.ingress.clusterIssuer }}
spec:
  tls:
    - hosts:
        - {{ .Values.grafana.ingress.hostUrl }}
      secretName: hello-kubernetes-tls
  rules:
    - host: {{ .Values.grafana.ingress.hostUrl }}
      http:
        paths:
          - pathType: Prefix
            path: {{ .Values.grafana.ingress.backendPath }}
            backend:
              service:
                name: {{ include "monitoring.fullname" . }}-grafana
                port:
                  name: {{ .Values.grafana.service.portName }}