apiVersion: v1
kind: Secret
metadata:
  name: {{ include "monitoring.fullname" . }}-grafana
  labels:
  {{- include "monitoring.grafanaLabels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.grafana.secret.adminPasswordName }}: "{{ .Values.grafana.secret.adminPasswordValue | b64enc }}"