apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "monitoring.fullname" . }}-grafana
  labels:
  {{- include "monitoring.grafanaLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.grafana.deployment.replicaCount }}
  selector:
    matchLabels:
  {{- include "monitoring.grafanaSelectorLabels" . | nindent 6 }}
  serviceName: {{ .Chart.Name }}- {{.Values.grafana.serviceNameSuffix}}

  template:
    metadata:
      labels:
    {{- include "monitoring.grafanaSelectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: grafana-datasources-config
          configMap:
            name: {{ include "monitoring.fullname" . }}-grafana-datasources
        - name: grafana-dashboard-config
          configMap:
            name: {{ include "monitoring.fullname" . }}-grafana-dashboards
      initContainers:
        - name: "{{ include "monitoring.fullname" . }}-grafana-init"
          image: "{{ .Values.grafana.deployment.image.repository }}"
          imagePullPolicy: {{ .Values.grafana.deployment.image.pullPolicy }}
          command:
            - bash
          args:
            - -c
            - "mkdir -p {{ .Values.grafana.deployment.dashboardsPath }} ; wget {{ .Values.grafana.deployment.dashboardBaseURL }}/{{ .Values.grafana.deployment.dashboardFile }} -O {{ .Values.grafana.deployment.dashboardsPath }}/{{ .Values.grafana.deployment.dashboardFile }}"
          volumeMounts:
            - name: {{ .Values.grafana.pvc.name }}
              mountPath: {{ .Values.grafana.deployment.dataPath }}

      containers:
        - name: {{ include "monitoring.fullname" . }}-grafana
          image: {{ .Values.grafana.deployment.image.repository }}:{{ .Values.grafana.deployment.image.tag }}
          imagePullPolicy: {{ .Values.grafana.deployment.image.pullPolicy }}
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "{{ .Values.grafana.deployment.adminPassword }}"

          ports:
            - name: grafana
              containerPort: {{ .Values.grafana.listenPort }}
              protocol: TCP
          volumeMounts:
            - name: {{ .Values.grafana.pvc.name }}
              mountPath: {{ .Values.grafana.deployment.dataPath }}
            - name: grafana-datasources-config
              mountPath: {{ .Values.grafana.deployment.datasourcesPath }}
            - name: grafana-dashboard-config
              mountPath: {{ .Values.grafana.deployment.dashboardProvidersPath }}

  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.grafana.pvc.name }}
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.grafana.pvc.size }}
        storageClassName: {{ .Values.storage.className }}