apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "monitoring.fullname" . }}-prometheus
  labels:
    {{- include "monitoring.prometheusLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.prometheus.deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "monitoring.prometheusSelectorLabels" . | nindent 6 }}
  serviceName: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        {{- include "monitoring.prometheusSelectorLabels" . | nindent 8 }}
    spec:
      securityContext:
      {{- toYaml .Values.prometheus.deployment.podSecurityContext | nindent 8 }}
      volumes:
        - name: prometheus-config
          configMap:
            name: {{ include "monitoring.fullname" . }}-prometheus
      containers:
        - name: {{ include "monitoring.fullname" . }}-prometheus
          image: {{ .Values.prometheus.deployment.image.repository }}:{{ .Values.prometheus.deployment.image.tag }}
          imagePullPolicy: {{ .Values.prometheus.deployment.image.pullPolicy }}
          args:
          - --config.file={{ .Values.prometheus.configPath }}/prometheus.yml
          - --storage.tsdb.retention.time=31d
          ports:
            - name: prometheus
              containerPort: {{ .Values.prometheus.listenPort }}
              protocol: TCP
          volumeMounts:
            - name: {{ .Values.prometheus.pvc.name }}
              mountPath: {{ .Values.prometheus.dataPath }}
            - name: prometheus-config
              mountPath: {{ .Values.prometheus.configPath }}
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.prometheus.pvc.name }}
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.prometheus.pvc.size }}
        storageClassName: {{ .Values.storage.className }}