nameOverride: ""
fullnameOverride: ""

prometheus:
  validatorMetricsUrl: validator-metrics
  beaconNodeMetricsUrl: beacon-node-metrics
  defaultMetricsPort: 8080
  persistentStorageSize: 5Gi
  listenPort: 9090
  dataPath: "/prometheus"
  configPath: "/etc/prometheus"

  serviceNameSuffix: prometheus
  deployment:
    replicaCount: 1
    podSecurityContext:
      runAsUser: 65534
      runAsGroup: 65534
      fsGroup: 65534
    image:
      repository: "prom/prometheus"
      pullPolicy: Always
      tag: "latest"

    healthEndpoint: "/healthz"
    beaconNode: beacon-node-grcp
  pvc:
    name: prometheus-pvc
    size: 10Gi

grafana:
  persistentStorageSize: 1Gi
  listenPort: 3000
  serviceNameSuffix: grafana
  deployment:
    podSecurityContext:
      runAsUser: 472
      runAsGroup: 472
      fsGroup: 472
    replicaCount: 1
    image:
      repository: grafana/grafana
      tag: latest
      pullPolicy: Always
    dataPath: "/var/lib/grafana"
    datasourcesPath: "/etc/grafana/provisioning/datasources"
    dashboardProvidersPath: "/etc/grafana/provisioning/dashboards"
    dashboardsPath: "/var/lib/grafana/dashboards"
    dashboardBaseURL: "https://raw.githubusercontent.com/GuillaumeMiralles/prysm-grafana-dashboard/master/"
    dashboardFile: "less_10_validators.json"
  pvc:
    name: grafana-pvc
    size: 2Gi
  service:
    portName: grafana
  secret:
    adminPasswordName: "adminPassword"
    adminPasswordValue: "overwrite-me"
  ingress:
    hostUrl: "qa.eth2.sigdevops.io"
    backendPath: "/"
    clusterIssuer: cluster-issuer-cert-manager-resources-qa

ports:
  metrics: 8080

storage:
  className: do-block-storage