apiVersion: v1
kind: Secret
metadata:
  name: {{ include "validator.fullname" . }}
  labels:
  {{- include "validator.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.validator.wallet.walletSecretName}}: "{{ .Values.validator.wallet.walletPassword | b64enc }}"
    {{ .Values.validator.webUi.passwordHash.fileName}}: "{{ .Values.validator.webUi.passwordHash | b64enc }}"