apiVersion: v1
kind: Secret
metadata:
  name: {{ include "validator.fullname" . }}
  labels:
  {{- include "validator.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.validator.wallet.secretName}}: "{{ .Values.validator.wallet.password | b64enc }}"