apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "beacon-node.fullname" . }}
  labels:
    {{- include "beacon-node.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.beaconNode.deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "beacon-node.selectorLabels" . | nindent 6 }}
  serviceName: {{ .Chart.Name }}

  template:
    metadata:
      labels:
        {{- include "beacon-node.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
      - name: configfile
        configMap:
          name: {{ include "beacon-node.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.beaconNode.deployment.image.repository }}:{{ .Values.beaconNode.deployment.image.tag }}
          args:
            - "--config-file={{ .Values.beaconNode.deployment.nodeConfigDir }}/{{ .Values.beaconNode.deployment.nodeConfigName }}"
            - "--accept-terms-of-use"
            {{- if .Values.beaconNode.isTestNet }}
            - "--pyrmont"
            {{- end }}
          imagePullPolicy: {{ .Values.beaconNode.deployment.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.ports.p2pTcp }}
              protocol: TCP
            - containerPort: {{ .Values.ports.p2pUdp }}
              protocol: UDP
            - name: grpc
              containerPort: {{ .Values.ports.grpc }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.ports.metrics }}
              protocol: TCP

          volumeMounts:
          - name: {{ .Values.beaconNode.data.pvcTemplateName }}
            mountPath: {{ .Values.beaconNode.data.dir }}
          - name: configfile
            mountPath: {{ .Values.beaconNode.deployment.nodeConfigDir }}
            readOnly: true

          resources:
            requests:
              memory: "4Gi"
              cpu: "2"
            limits:
              memory: "6Gi"
              cpu: "3.5"
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.beaconNode.data.pvcTemplateName }}
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.beaconNode.data.pvcSize }}
        storageClassName: {{ .Values.storage.className }}