{{- if .Values.storage.useStorage }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "beacon-node.fullname" . }}
  labels:
  {{- include "beacon-node.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.storage.className }}
  storageClassName: microk8s-hostpath
  {{- end }}
  resources:
    requests:
      storage: 20Gi
{{- end }}