---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: diekirch-donkey
  region: ap-northeast-1

fargateProfiles:
  - name: fp-default
    selectors:
      - namespace: default
      - namespace: kube-system
      - namespace: nginx
  - name: fp-prysm
    selectors:
      - namespace: prysm