apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "cert-manager-resources.fullname" . }}-{{ .Values.stage }}
spec:
  acme:
    # Email address used for ACME registration
    email: {{ .Values.acme.emailAddress }}
    server: {{ .Values.acme.server }}
    privateKeySecretRef:
      # Name of a secret used to store the ACME account private key
      name: letsencrypt-{{ .Values.stage }}-private-key
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
      - http01:
          ingress:
            class: nginx