nameOverride: ""
fullnameOverride: ""

beaconNode:
  isTestNet: "<set-in-stage-specific-charts>"
  web3HttpProvider: "<pass-as-parameter>"
  p2pHostDns: ""
  deployment:
    replicaCount: "<set-in-stage-specific-charts>"
    podSecurityContext:
      runAsUser: 101
      runAsGroup: 101
      fsGroup: 101
    image:
      repository: "gcr.io/prysmaticlabs/prysm/beacon-chain"
      pullPolicy: Always
      tag: "stable"
      useDebug: false
      debugTag: "latest-debug"
    nodeConfigDir: "/config"
    nodeConfigName: "beacon.yaml"
  data:
    dir: "/data"
    pvcSize: 80Gi
    pvcTemplateName: node-data-pvc

stats:
  deployment:
    replicaCount: 1
    image:
      repository: "alethio/eth2stats-client"
      pullPolicy: Always
      tag: "latest"
    eth2StatsAddr: "grpc.medalla.eth2stats.io:443"
    eth2StatsTLS: "true"
    name: "stats-node"
    beaconType: "prysm"
    nodeName: "withte.eth"
  data:
    dir: "/data"
    pvcSize: 5Gi
    pvcTemplateName: node-stats-pvc

ports:
  p2pTcp: 13000
  p2pUdp: 12000
  grpc: 4000
  metrics: 8080

storage:
  className: do-block-storage

service:
  useTcp: false
  useUdp: false
  type: ClusterIP

