nameOverride: ""
fullnameOverride: ""

deployment:
  replicaCount: 1
  image:
    repository: "gcr.io/prysmaticlabs/prysm/validator"
    pullPolicy: Always
    tag: "stable"

  healthEndpoint: "/healthz"
  configDir: "/config"
  configName: "validator.yaml"

  beaconNode: beacon-node-grcp

ports:
  metrics: 8080

graffiti: ""

wallet:
  walletDirectory: "/wallet"
  walletPassword: "<pass-as-parameter>"
  walletPasswordFilePath: "/wallet/wallet-password"
  walletSecretSubPath: "wallet-password"
  awsS3Init:
    awsRegion: "us-east-1"
    accessKeyId: "<pass-as-parameter>"
    secretAccessKey: "<pass-as-parameter>"
    walletPath: "<pass-as-parameter>"