nameOverride: ""
fullnameOverride: ""

deployment:
  replicaCount: 1
  image:
    repository: "gcr.io/prysmaticlabs/prysm/validator"
    pullPolicy: Always
    useDebug: false
    stableTag: "stable"
    debugTag: "latest-debug"

  healthEndpoint: "/healthz"
  configDir: "/config"
  configName: "validator.yaml"

  beaconNode: beacon-node-grcp

ports:
  metrics: 8080



validator:
  useTestnet: true
  graffiti: ""

  webUi:
    activateWebUi: true
    passwordHash:
      secretName: webUiPasswordHash
      secretValue: "<pass-as-parameter>"
      fileName: rpc-password-hash
      filePath: /wallet

  wallet:
    walletVolumeName: "wallet-volume"
    walletDirectory: "/wallet"
    walletPassword: "<pass-as-parameter>"
    walletPasswordFilePath: "/wallet-password"
    walletSecretVolumeName: "wallet-password"
    walletSecretName: "wallet-password"
    awsS3Init:
      awsRegion: "us-east-1"
      accessKeyId: "<pass-as-parameter>"
      secretAccessKey: "<pass-as-parameter>"
      walletPath: "<pass-as-parameter>"
      walletFileName: "wallet.tar.gz"