apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "beacon-node.fullname" . }}-stats
  labels:
  {{- include "beacon-node.statsLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.stats.deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "beacon-node.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "beacon-node.fullname" . }}-stats

  template:
    metadata:
      labels:
        {{- include "beacon-node.selectorLabels" . | nindent 8 }}
    spec:

      containers:
      - name: {{ include "beacon-node.fullname" . }}-stats
        image: {{ .Values.stats.deployment.image.repository }}:{{ .Values.stats.deployment.image.tag }}
        imagePullPolicy: {{ .Values.stats.deployment.image.pullPolicy }}
        args:
          - "run"
          - "--eth2stats.node-name={{ .Values.stats.deployment.nodeName }}"
          - "--data.folder={{ .Values.stats.deployment.dataPath }}"
          - "--eth2stats.addr={{ .Values.stats.deployment.eth2StatsAddr }}"
          - "--eth2stats.tls={{ .Values.stats.deployment.eth2StatsTLS }}"
          - "--beacon.type={{ .Values.stats.deployment.beaconType }}"
          - "--beacon.addr={{ include "beacon-node.fullname" . }}-grcp:{{ .Values.ports.grpc }}"
          - "--beacon.metrics-addr=http://{{ include "beacon-node.fullname" . }}-metrics:{{ .Values.ports.metrics }}/metrics"
        volumeMounts:
        - mountPath: {{ .Values.stats.data.dir }}
          name: {{ .Values.stats.data.pvcTemplateName }}
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.stats.data.pvcTemplateName }}
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.stats.data.pvcSize}}
        storageClassName: {{ .Values.storage.className }}