name: Deploy-Beacon-Node

on:
  workflow_dispatch:

env:
  EKS_CLUSTER_NAME: elmo
  AWS_REGION: us-east-1

jobs:
  deploy-node:
    name: Deploy beacon node
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code base
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v1

      - name: Install helm
        uses: azure/setup-helm@v1

      - name: Create kubeconfig
        run: |
          aws eks update-kubeconfig --name ${EKS_CLUSTER_NAME}

      - name: Install beacon node
        run: |
          helm upgrade -i \
            --name beacon-node \
            --namespace prysm \
            -f helm/beacon-node/values.yaml \
            --set beaconNode.web3HttpProvider=${{ secrets.INFURA_GOERLI_GETH_ENDPOINT }} \
            helm/beacon-node
