name: Create-DO-Cluster

on: workflow_dispatch

env:
  CLUSTER_NAME: elmo
  K8S_VERSION: 1.20.2-do.0

jobs:
  create-cluster:
    name: Create the Digital Ocean cluster
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_API_TOKEN }}
      - name: Create cluster
        run: |
          if ! $(doctl kubernetes cluster get ${CLUSTER_NAME} &> /dev/null); then
            echo "Creating cluster ${CLUSTER_NAME}"
            doctl kubernetes cluster create ${CLUSTER_NAME} \
                        --node-pool "name=${CLUSTER_NAME}-nodepool;size=s-4vcpu-8gb;count=2" \
                        --region fra1 \
                        --version ${K8S_VERSION} \
                        --wait
          else
            echo "Cluster ${EKS_CLUSTER_NAME} already created"
          fi

      - name: Install kubectl
        uses: azure/setup-kubectl@v1

      - name: Create kubeconfig
        run: |
          doctl kubernetes cluster kubeconfig save ${CLUSTER_NAME}

      - name: Create namespace ethereum
        run: |
          kubectl create namespace ethereum