name: Deploy-DO-Validator

on:
  push:
    paths:
      - prysm/validator/*
      - prysm/validator
  workflow_dispatch:
    inputs:
      useDebug:
        description: Deploy latest images in debug mode
        default: false


env:
  CLUSTER_NAME: elmo
  ETHEREUM_NAMESPACE: ethereum

jobs:
  deploy-node:
    name: Deploy validator to Digital Ocean
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code base
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_API_TOKEN }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v1

      - name: Install helm
        uses: azure/setup-helm@v1

      - name: Create kubeconfig
        run: |
          doctl kubernetes cluster kubeconfig save ${CLUSTER_NAME}

      - name: Install validator
        run: |
          helm upgrade \
            validator \
            prysm/validator \
            -i \
            --namespace ${ETHEREUM_NAMESPACE} \
            -f prysm/validator/values.yaml \
            --set validator.wallet.walletPassword=${{ secrets.PRYSM_VALIDATOR_WALLET_PASSWORD }} \
            --set validator.wallet.awsS3Init.accessKeyId=${{ secrets.AWS_ACCESS_KEY_ID }} \
            --set validator.wallet.awsS3Init.secretAccessKey=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            --set validator.wallet.awsS3Init.walletPath=${{ secrets.PRYSM_VALIDATOR_WALLET_S3_PATH }} \
            --set deployment.image.useDebug=${{ github.event.inputs.useDebug }} \
            --debug