name: Init-EKS-Cluster

on: workflow_dispatch

jobs:
  create-cluster:
    name: Initialize the EKS cluster named elmo
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Add identity mapping for core user
        uses: robatwave/github-action-eksctl@0.1.2
        with:
          args: create iamidentitymapping --cluster  elmo --arn arn:aws:iam::514125260731:user/jens --group system:masters --username admin

      - name: Create kubeconfig
        run: |
          aws eks update-kubeconfig --name elmo

      - name: Install kubectl
        uses: azure/setup-kubectl@v1

      - name: Create and use prysm namespace
        run: |
          kubectl create namespace horst --dry-run=client -o yaml | kubectl apply -f -
          kubectl config set-context --current --namespace prysm