name: Init-EKS-Cluster

on: workflow_dispatch

jobs:
  create-cluster:
    name: Initialize the EKS cluster named elmo
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Download eksctl
        run: |
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin

      - name: Add identity mapping for core user
        run: |
          eksctl create iamidentitymapping --cluster  elmo --arn arn:aws:iam::514125260731:user/jens --group system:masters --username admin

      - name: Create kubeconfig
        run: |
          aws eks update-kubeconfig --name elmo

      - name: Install kubectl
        uses: azure/setup-kubectl@v1

      - name: Create and use prysm namespace
        run: |
          kubectl create namespace prysm --dry-run=client -o yaml | kubectl apply -f -
          kubectl config set-context --current --namespace prysm