name: Teardown-EKS-Cluster

on: workflow_dispatch

env:
  EKS_CLUSTER_NAME: elmo
  AWS_ACCOUNT_ID: 514125260731
  AWS_REGION: us-east-1
  LOAD_BALANCER_POLICY_NAME: AWSLoadBalancerControllerIAMPolicy

jobs:
  destroy-cluster:
    name: Destroy the EKS cluster named elmo
    runs-on: ubuntu-latest
    steps:
      - name: checkout-code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Download eksctl
        run: |
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin

      - name: Delete eks cluster via eksctl
        run: |
          eksctl delete cluster --name ${EKS_CLUSTER_NAME} --wait

      - name: Delete Load Balancer controller IAM policy
        run: |
          aws iam delete-policy --policy-arn arn:aws:iam::${AWS_ACCOUNT_ID}:policy/${LOAD_BALANCER_POLICY_NAME}
