name: Teardown-EKS-Cluster

on: workflow_dispatch

jobs:
  destroy-cluster:
    name: Destroy the EKS cluster named elmo
    runs-on: ubuntu-latest
    steps:
      - name: checkout-code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Download eksctl
        run: |
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin

      - name: Delete eks cluster via eks
        run: |
          eksctl delete cluster --name elmo --wait